language: python
python:
  - "3.6"
  
# command to install dependencies
install:
  - python -m pip install -r requirements.txt
  - aws configure set profile.testing.aws_access_key_id $aws_access_key_id
  - aws configure set profile.testing.aws_secret_access_key $aws_secret_access_key
  - aws configure set profile.testing.region ap-southeast-2
  - aws configure set profile.testing.output json

# command to run tests
script:
  - python deploy.py
