language: python
python:
  - "3.6"
  
# command to install dependencies
install:
  - python -m pip install -r requirements.txt
  - export AWS_DEFAULT_REGION=ap-southeast-2

# command to run tests
script:
  - python deploy.py
